CREATE TABLE persona
(
    persona_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    CONSTRAINT pk_persona
        PRIMARY KEY (persona_id)
);

CREATE TABLE usuario
(
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persona_id BIGINT NULL,
    nombre VARCHAR(200) NOT NULL,
    correo VARCHAR(320) NOT NULL,
    origen_codigo CHAR(1) NOT NULL,
    tipo_cuenta_codigo CHAR(1) NOT NULL,
    estado_cuenta_codigo INTEGER NOT NULL,
    fecha_inicio_vigencia DATE NOT NULL,
    fecha_fin_vigencia DATE NOT NULL,
    estado_registro BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    actor_creacion_id BIGINT NOT NULL,
    fecha_modificacion TIMESTAMP(6) NULL,
    actor_modificacion_id BIGINT NULL,

    CONSTRAINT pk_usuario
        PRIMARY KEY (usuario_id),

    CONSTRAINT fk_usuario_persona
        FOREIGN KEY (persona_id)
            REFERENCES persona(persona_id),

    CONSTRAINT ck_usuario_origen_codigo
        CHECK (origen_codigo IN ('I', 'E')),

    CONSTRAINT ck_usuario_tipo_cuenta_codigo
        CHECK (tipo_cuenta_codigo IN ('P', 'A', 'S', 'O')),

    CONSTRAINT ck_usuario_estado_cuenta_codigo
        CHECK (estado_cuenta_codigo IN (1, 2, 3, 4, 5, 6)),

    CONSTRAINT ck_usuario_periodo_vigencia
        CHECK (fecha_fin_vigencia >= fecha_inicio_vigencia),

    CONSTRAINT ck_usuario_auditoria_modificacion
        CHECK
            (
            (
                fecha_modificacion IS NULL
                    AND actor_modificacion_id IS NULL
                )
                OR
            (
                fecha_modificacion IS NOT NULL
                    AND actor_modificacion_id IS NOT NULL
                )
            )
);

CREATE UNIQUE INDEX uq_usuario_correo_normalizado
    ON usuario (LOWER(correo));